Resources:
  # The main topic where all the messages related to orders are published
  OrdersTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: OrdersTopic
      FifoTopic: false
      TopicName: OrdersTopic

  # Queue that will receive message from the OrdersTopic and will be used by the Order processor Lambda function
  OrderProcessingQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: OrderProcessingQ
      VisibilityTimeout: 35
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt OrderProcessingDLQ.Arn
        maxReceiveCount: 5

  OrderProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: OrderProcessingDLQ

  # Connected to Fulfilment processor lambda function
  FulfilmentProcessingQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: FulfilmentProcessingQ
      VisibilityTimeout: 35
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt FulfilmentProcessingDLQ.Arn
        maxReceiveCount: 5
        
  FulfilmentProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: FulfilmentProcessingDLQ

  # Connected to Payment processor lambda function
  PaymentProcessingQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: PaymentProcessingQ
      VisibilityTimeout: 35
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt PaymentProcessingDLQ.Arn
        maxReceiveCount: 5
  
  PaymentProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: PaymentProcessingDLQ

  # Allow SNS Topic to publish to SQS Queues
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref OrderProcessingQ
        - !Ref FulfilmentProcessingQ
        - !Ref PaymentProcessingQ
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: 
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: '*'
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref OrdersTopic

  # SNS Subscriptions
  OrderProcessingSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt OrderProcessingQ.Arn
      Protocol: sqs
      TopicArn: !Ref OrdersTopic
      # RawMessageDelivery: true
