service: event-driven-coffee

frameworkVersion: '3'

configValidationMode: error

plugins:
  - serverless-esbuild

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-southeast-2
  profile: dina # replace this with appropriate profile
  tags:
    SERVICE: event-driven-coffee
    STAGE: ${self:provider.stage}
  deploymentMethod: direct
  memorySize: 512
  timeout: 30
  logRetentionInDays: 7
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: !Ref OrdersTopic

  environment:
    ORDERS_SNS_TOPIC_ARN: !Ref OrdersTopic

functions:
  processOrder:
    handler: packages/backend-order/src/handler.processOrder
    events:
      - sqs:
          arn: !GetAtt OrderProcessingQ.Arn

  placeOrder:
    handler: packages/backend-order/src/handler.placeOrder
    events:
      - http:
          path: /order
          method: post
          cors: true

resources: ${file(resources.yml)}

custom:
  esbuild:
    bundle: true
    minify: false
