service: backend-payment

frameworkVersion: '3'

configValidationMode: error

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-southeast-2
  profile: np-nonprod-1 # replace this with appropriate profile
  tags:
    SERVICE: event-driven-coffee
    STAGE: ${self:provider.stage}
  deploymentMethod: direct
  memorySize: 512
  timeout: 30
  logRetentionInDays: 3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: ${param:OrderTopic}
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: !GetAtt OrderTable.Arn

  environment:
    ORDERS_SNS_TOPIC_ARN: ${param:OrderTopic}
    PAYMENT_TABLE_NAME: !Ref PaymentTable

functions:
  authorizerFunction: 
    handler: src/authorizer/index.handler

  paymentApi: 
    handler: src/api/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          authorizer: 
            name: authorizerFunction
            identitySource: method.request.header.x-secret-key

  paymentEventProcessor:
    handler: src/event-processor/index.handler
    events:
      - sqs:
          arn: !GetAtt PaymentProcessingQ.Arn
          batchSize: 5

resources:
  Resources:
    # Connected to Payment processor lambda function
    PaymentProcessingQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: PaymentProcessingQ.fifo
        FifoQueue: true
        VisibilityTimeout: 35
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt PaymentProcessingDLQ.Arn
          maxReceiveCount: 5

    PaymentProcessingDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: PaymentProcessingDLQ.fifo
        FifoQueue: true

    PaymentProcessingQPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref PaymentProcessingQ
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Action: sqs:SendMessage
              Resource: !GetAtt PaymentProcessingQ.Arn

    PaymentProcessingQSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: !GetAtt PaymentProcessingQ.Arn
        Protocol: sqs
        TopicArn: ${param:OrderTopic}

    PaymentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PaymentTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: orderDate
            AttributeType: S
          - AttributeName: createdTimestamp
            AttributeType: 'N'
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: orderDateIndex
            Projection:
              ProjectionType: ALL
            KeySchema:
              - AttributeName: orderDate
                KeyType: HASH
              - AttributeName: createdTimestamp
                KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

custom:
  esbuild:
    bundle: true
    minify: false
