service: backend-notifier

frameworkVersion: '3'

configValidationMode: error
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-southeast-2
  profile: np-nonprod-1 # replace this with appropriate profile
  tags:
    SERVICE: event-driven-coffee
    STAGE: ${self:provider.stage}
  deploymentMethod: direct
  memorySize: 512
  timeout: 30
  logRetentionInDays: 3
  environment:
    GRAPHQL_API_URL: ${env:GRAPHQL_API_URL}

functions:
  eventProcessor:
    handler: src/index.handler
    events:
      - sqs:
          arn: !GetAtt NotifierQ.Arn
          batchSize: 5

resources:
  Resources:
    NotifierQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: NotifierQ.fifo
        FifoQueue: true
        VisibilityTimeout: 35
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt NotifierDLQ.Arn
          maxReceiveCount: 5

    NotifierDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: NotifierDLQ.fifo
        FifoQueue: true

    NotifierQPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref NotifierQ
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Action: sqs:SendMessage
              Resource: !GetAtt NotifierQ.Arn

    NotifierQSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: !GetAtt NotifierQ.Arn
        Protocol: sqs
        TopicArn: ${param:OrderTopic}

custom:
  esbuild:
    bundle: true
    minify: false
